FROM mono:latest

COPY . .
RUN msbuild SagaECO.sln


FROM mono:latest
COPY --from=0 /SagaLogin/bin/Debug/ .
COPY --from=0 /SagaScript/bin/Debug/SagaScript.dll ./Scripts/
COPY Configuration/ .

ENTRYPOINT [ "mono", "SagaLogin.exe" ]