name: DEPLOY-PRD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  # build:
  #   name: Build & Push Docker image to Docker Hub
  #   runs-on: ubuntu-latest

  #   steps:
  #   - name: Check out the repo
  #     uses: actions/checkout@v2
    
  #   - uses: nuget/setup-nuget@v1
  #     with:
  #       nuget-version: 'latest'
    
  #   - run: nuget restore SagaECO.sln


  #   - name: Set up QEMU
  #     uses: docker/setup-qemu-action@v1
    
  #   - name: Set up Docker Buildx
  #     uses: docker/setup-buildx-action@v1

  #   - name: Log in to Docker Hub
  #     uses: docker/login-action@v1
  #     with:
  #       username: ${{ secrets.DOCKER_USERNAME }}
  #       password: ${{ secrets.DOCKER_PASSWORD }}
    
    
  #   - name: Build and push
  #     run: |
  #       docker build -t kietara/sagalogin:latest -f dockerfile-login .
  #       docker build -t kietara/sagamap:latest -f dockerfile-map .
  #       docker push kietara/sagalogin:latest
  #       docker push kietara/sagamap:latest
      

  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    # needs: [build]

    environment:
      name: Production
      url: 'https://econline.org'
    
    steps:
    - name: copy file script
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.BOKIE_SERVER_HOST }}
        username: ${{ secrets.BOKIE_SERVER_USERNAME }}
        password: ${{ secrets.BOKIE_SERVER_PASSWORD }}
        port: ${{ secrets.BOKIE_SERVER_PORT }}
        source: "deploy.bat"
        target: "C:\\Users\\Bokie"

    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.BOKIE_SERVER_HOST }}
        username: ${{ secrets.BOKIE_SERVER_USERNAME }}
        password: ${{ secrets.BOKIE_SERVER_PASSWORD }}
        port: ${{ secrets.BOKIE_SERVER_PORT }}
        script: |
          # saga.bat
          dir