name: UPDATE-SCRIPT

on:
  push:
    branches:
      - feature/script
  pull_request:
    branches:
      - feature/script
  workflow_dispatch:

jobs:
  script:
    name: Update Script
    runs-on: windows-latest

    environment:
      name: Production
    
    steps:
    - uses: actions/checkout@v2
      with:
        ref: feature/script

    - uses: nuget/setup-nuget@v1
      with:
        nuget-version: 'latest'
    
    - run: nuget restore SagaECO.sln

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.3

    - run: msbuild.exe SagaECO.sln

  db:
    name: Update DB
    runs-on: ubuntu-latest

    environment:
      name: Production
    
    steps:
    - name: Update DB
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.BOKIE_SERVER_HOST }}
        username: ${{ secrets.BOKIE_SERVER_USERNAME }}
        password: ${{ secrets.BOKIE_SERVER_PASSWORD }}
        port: ${{ secrets.BOKIE_SERVER_PORT }}
        script: sagasc.bat