name: UPDATE-SCRIPT

on:
  push:
    branches:
      - feature/script
  pull_request:
    branches:
      - feature/script
  workflow_dispatch:

jobs:
  script:
    name: Update Script
    runs-on: windows-latest

    environment:
      name: Production
    
    steps:
    - uses: actions/checkout@v2
      with:
        ref: feature/script

    - uses: nuget/setup-nuget@v1
      with:
        nuget-version: 'latest'
    
    - run: nuget restore SagaECO.sln

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.3

    - run: msbuild.exe SagaECO.sln

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: SagaScript
        path: 'D:\\a\\SagaECO\\SagaScript\\bin\\Debug\\SagaScript.dll'

    # - name: copy file via ssh password
    #   uses: appleboy/scp-action@master
    #   with:
    #     host: ${{ secrets.BOKIE_SERVER_HOST }}
    #     username: ${{ secrets.BOKIE_SERVER_USERNAME }}
    #     password: ${{ secrets.BOKIE_SERVER_PASSWORD }}
    #     port: ${{ secrets.BOKIE_SERVER_PORT }}
    #     source: "D:\\a\\SagaECO\\SagaECO\\SagaScript.dll"
    #     target: "C:\\Users\\Bokie\\script\\SagaScript.dll"


  db:
    name: Update DB
    runs-on: ubuntu-latest

    environment:
      name: Production
    
    steps:
    - name: Update DB
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.BOKIE_SERVER_HOST }}
        username: ${{ secrets.BOKIE_SERVER_USERNAME }}
        password: ${{ secrets.BOKIE_SERVER_PASSWORD }}
        port: ${{ secrets.BOKIE_SERVER_PORT }}
        script: sagasc.bat