name: UPDATE-SCRIPT

on:
  push:
    branches:
      - feature/script
  pull_request:
    branches:
      - feature/script
  workflow_dispatch:

jobs:
  script:
    name: Update Script
    runs-on: ubuntu-latest

    environment:
      name: Production
      url: 'https://econline.org'
    
    steps:
    # - uses: nuget/setup-nuget@v1
    #   with:
    #     nuget-version: 'latest'
    
    # - run: nuget restore SagaECO.sln

    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      # with:
      #   dotnet-version: '2.1.x'

    - run: dotnet build SagaECO.sln

    - name: Update
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.BOKIE_SERVER_HOST }}
        username: ${{ secrets.BOKIE_SERVER_USERNAME }}
        password: ${{ secrets.BOKIE_SERVER_PASSWORD }}
        port: ${{ secrets.BOKIE_SERVER_PORT }}
        script: sagasc.bat